Repository PlayFab/thundernetes, pull requests merged in 2021-11, with the labels that each got.

#51 Created prerequisites.md
  docs/prerequisites.md
Labels: documentation

#48 Better tracking ConnectedPlayers
  docs/architecture.md
  docs/development.md
  e2e/cmd/main.go
  e2e/cmd/utilities.go
  operator/PROJECT
  operator/api/v1alpha1/gameserver_types.go
  operator/api/v1alpha1/gameserverdetail_types.go
  operator/api/v1alpha1/zz_generated.deepcopy.go
  operator/config/crd/bases/mps.playfab.com_gameserverdetails.yaml
  operator/config/crd/bases/mps.playfab.com_gameservers.yaml
  operator/config/crd/kustomization.yaml
  operator/config/crd/patches/cainjection_in_gameserverdetails.yaml
  operator/config/crd/patches/webhook_in_gameserverdetails.yaml
  operator/config/manager/kustomization.yaml
  operator/config/rbac-gameserver-editor/gameserver_editor_role.yaml
  operator/config/rbac/gameserverdetail_editor_role.yaml
  operator/config/rbac/gameserverdetail_viewer_role.yaml
  operator/config/rbac/role.yaml
  operator/controllers/gameserver_controller.go
  operator/http/allocate.go
  samples/netcore/Controllers/HelloController.cs
  samples/netcore/Startup.cs
  sidecar-go/go.mod
  sidecar-go/go.sum
  sidecar-go/httphandler.go
  sidecar-go/httphandler_test.go
  sidecar-go/main.go
Labels: enhancement, area/tests

#50 adding logrus to initcontainer
  docs/gameserverbuild.md
  initcontainer/go.mod
  initcontainer/go.sum
  initcontainer/main.go
  operator/config/manager/kustomization.yaml
  operator/controllers/utilities.go
Labels: enhancement, area/user-experiences

#59 fixing PodAffinity FAQ
  docs/FAQ.md
Labels: documentation

#62 renaming CRD instance to CR
  operator/controllers/gameserverbuild_controller_test.go
  sidecar-go/httphandler.go
Labels: priority/low

#58 fix for GsdkConfig
  .github/workflows/main.yml
  initcontainer/go.mod
  initcontainer/go.sum
  initcontainer/main.go
  initcontainer/main_test.go
Labels: bug, enhancement

#55 adding uninstall information
  docs/quickstart.md
  operator/config/manager/kustomization.yaml
Labels: documentation

#63 Created troubleshooting guide and categories
  docs/troubleshooting/Cluster/README.md
  docs/troubleshooting/Deployment/README.md
  docs/troubleshooting/GameServers/HowCanIFindThePublicIPAddress.md
  docs/troubleshooting/GameServers/HowCanIRunMyGameServerPodInANonDefaultNamespace.md
  docs/troubleshooting/GameServers/HowToScheduleGameServerNodes.md
  docs/troubleshooting/GameServers/MyGameServerIsStuck.md
  docs/troubleshooting/GameServers/README.md
  docs/troubleshooting/Kubernetes/README.md
  docs/troubleshooting/Metrics/README.md
  docs/troubleshooting/README.md
  docs/troubleshooting/Security/README.md
Labels: documentation

#64 Updated README.md
  README.md
Labels: documentation

#66 refactoring sidecar
  sidecar-go/main.go
  sidecar-go/sidecarmanager.go
  sidecar-go/sidecarmanager_test.go
Labels: refactoring

#70 adding release shield
  README.md
Labels: documentation

#93 updating docs
  README.md
  docs/FAQ.md
  docs/architecture.md
  docs/gameserverlifecycle.md
  docs/prerequisites.md
  docs/quickstart.md
  docs/resources.md
  docs/yourgameserver.md
Labels: documentation
