Repository PlayFab/thundernetes, pull requests merged in 2022-07, with the labels that each got.

#291 Add node scaling to e2e tests
  cmd/e2e/build_crashing_test.go
  cmd/e2e/scale_nodes_test.go
  e2e/run.sh
  installfiles/operator.yaml
  installfiles/operator_with_monitoring.yaml
  installfiles/operator_with_security.yaml
  installfiles/operator_with_security_and_monitoring.yaml
  pkg/operator/config/e2e/kustomization.yaml
  pkg/operator/config/e2e/manager_e2e.yaml
  pkg/operator/config/manager/manager.yaml
  pkg/operator/controllers/port_registry.go
  pkg/operator/main.go
Labels: area/tests

#293 Ignoring GameServer Health state from heartbeat
  cmd/nodeagent/main.go
  cmd/nodeagent/nodeagentmanager.go
  cmd/nodeagent/nodeagentmanager_test.go
Labels: enhancement

#303 modifying CI GitHub action
  .github/workflows/main.yml
Labels: area/build-tools

#305 refactoring quickstart
  docs/404.html
  docs/Gemfile.lock
  docs/howtos/uninstallthundernetes.md
  docs/quickstart.md
  docs/quickstart/allocation-scaling.md
  docs/quickstart/create-k8s-cluster.md
  docs/quickstart/installing-aks.md
  docs/quickstart/installing-kind.md
  docs/quickstart/installing-thundernetes.md
  docs/quickstart/sample-dotnet.md
  docs/quickstart/sample-openarena.md
  docs/quickstart/samples.md
Labels: documentation

#308 docs updates
  docs/Gemfile.lock
  docs/README.md
  docs/_config-development.yml
  docs/architecture.md
  docs/development.md
  docs/gameserverbuild.md
  docs/gameserverlifecycle.md
  docs/howtos/runlocalmultiplayeragent.md
  docs/howtos/uninstallthundernetes.md
  docs/howtos/upgradebuild.md
  docs/howtos/usingwrapper.md
  docs/prerequisites.md
  docs/quickstart/installing-thundernetes.md
  docs/quickstart/sample-dotnet.md
  docs/yourgameserver.md
Labels: documentation

#309 fixing deletion ordering
  pkg/operator/controllers/allocation_api_server_test.go
  pkg/operator/controllers/controller_utils.go
  pkg/operator/controllers/gameserverbuild_controller.go
  pkg/operator/controllers/gameserverbuild_controller_test.go
  pkg/operator/controllers/test_utils_test.go
Labels: area/user-experiences

#312 logging for PortRegistry
  cmd/e2e/scale_nodes_test.go
  pkg/operator/config/manager/manager.yaml
  pkg/operator/controllers/gameserver_controller.go
  pkg/operator/controllers/port_registry.go
  pkg/operator/controllers/port_registry_test.go
Labels: bug

#314 Added new docs about the GameServer API
  docs/FAQ.md
  docs/contributing.md
  docs/development.md
  docs/gameserverapi/README.md
  docs/gameserverapi/apidocs.md
  docs/howtos/README.md
  docs/thundernetesui/README.md
  docs/troubleshooting/README.md
Labels: documentation

#324 updates to GameServerBuild documentation
  docs/gameserverbuild.md
Labels: documentation

#322 Updated latency server docs
  docs/howtos/latencyserver.md
Labels: documentation

#323 Some minor updates
  docs/howtos/gameserverlogs.md
  samples/fluentbit/fluent-bit-ds.yaml
Labels: documentation

#326 Intelligent scaling documentation
  cmd/standby-forecaster/README.md
  cmd/standby-forecaster/main.go
  docs/gameserverbuild.md
  docs/howtos/clusterautoscaling.md
  docs/howtos/customportrange.md
  docs/howtos/gameserverlogs.md
  docs/howtos/intelligentscaling.md
  docs/howtos/latencyserver.md
  docs/howtos/monitoring.md
  docs/howtos/nodepools.md
  docs/howtos/publicipaddress.md
  docs/howtos/scheduling.md
  docs/howtos/serviceingress.md
  docs/howtos/uninstallthundernetes.md
  docs/howtos/upgradebuild.md
  docs/howtos/usingwrapper.md
  docs/howtos/windowscontainers.md
  samples/server-load-simulator/simulator.yaml
  samples/standby-forecaster/forecaster.yaml
Labels: documentation

#337 Documentation updates take N of many
  docs/README.md
  docs/architecture.md
  docs/contributing.md
  docs/development/release.md
  docs/development/windows.md
  docs/gameserverbuild.md
  docs/gsdk/README.md
  docs/gsdk/gameserverlifecycle.md
  docs/gsdk/gsdkfooter.md
  docs/howtos/customportrange.md
  docs/howtos/gameserverlogs.md
  docs/howtos/hostnetworking.md
  docs/howtos/intelligentscaling.md
  docs/howtos/latencyserver.md
  docs/howtos/nodepools.md
  docs/howtos/publicipaddress.md
  docs/howtos/serviceingress.md
  docs/howtos/usingwrapper.md
  docs/howtos/windowscontainers.md
  docs/quickstart/allocation-scaling.md
Labels: documentation

#346 Hiding footer page from navigation
  docs/gsdk/gsdkfooter.md
Labels: documentation

#348 fixing footer
  docs/_includes/gsdkfooter.md
  docs/gsdk/csharpcppjava.md
  docs/gsdk/unity.md
  docs/gsdk/unreal.md
Labels: documentation

#351 adding a method to facilitate better test logging
  cmd/e2e/utilities_test.go
Labels: area/tests

#354 Fix for data race in heartBeatTimeChecker tests
  cmd/nodeagent/main.go
  cmd/nodeagent/nodeagentmanager.go
  cmd/nodeagent/nodeagentmanager_test.go
Labels: area/tests
