Repository PlayFab/thundernetes, pull requests merged in 2022-01, with the labels that each got.

#125 adding information about Pod Priority
  docs/FAQ.md
Labels: documentation

#126 Updated README.md
  docs/troubleshooting/README.md
Labels: documentation

#127 changing gs.Spec.PodSpec to PodTemplateSpec
  cmd/e2e/main.go
  docs/FAQ.md
  docs/gameserverbuild.md
  docs/yourgameserver.md
  pkg/operator/Makefile
  pkg/operator/api/v1alpha1/gameserver_types.go
  pkg/operator/api/v1alpha1/gameserverbuild_types.go
  pkg/operator/api/v1alpha1/zz_generated.deepcopy.go
  pkg/operator/config/crd/bases/mps.playfab.com_gameserverbuilds.yaml
  pkg/operator/config/crd/bases/mps.playfab.com_gameserverdetails.yaml
  pkg/operator/config/crd/bases/mps.playfab.com_gameservers.yaml
  pkg/operator/config/samples/netcore.yaml
  pkg/operator/controllers/gameserver_controller.go
  pkg/operator/controllers/gameserver_controller_test.go
  pkg/operator/controllers/gameserverbuild_controller_test.go
  pkg/operator/controllers/port_registry.go
  pkg/operator/controllers/suite_test.go
  pkg/operator/controllers/utilities.go
  pkg/operator/controllers/utilities_test.go
  pkg/operator/http/allocate_test.go
  samples/netcore/sample-hostnetwork.yaml
  samples/netcore/sample-nodeaffinity.yaml
  samples/netcore/sample-secondnodepool.yaml
  samples/netcore/sample.yaml
  samples/openarena/sample.yaml
  samples/unity/sample.yaml
Labels: area/user-experiences, breaking change

#137 documentation updates
  README.md
  docs/FAQ.md
  docs/architecture.md
  docs/development.md
  docs/gameserverbuild.md
  docs/gameserverlifecycle.md
  docs/prerequisites.md
  docs/quickstart.md
  docs/yourgameserver.md
  samples/openarena/Program.cs
  samples/unity/README.md
Labels: documentation

#144 rename to allocationapiserver
  pkg/operator/http/http.go
  pkg/operator/main.go
Labels: code-quality

#145 removing hardcoded json
  cmd/nodeagent/nodeagentmanager.go
Labels: code-quality

#147 fix crashes test
  cmd/e2e/utilities.go
Labels: area/tests

#146 additions for kubebuilder 3.2 and 3.3
  go.mod
  go.sum
  pkg/operator/.dockerignore
  pkg/operator/Makefile
  pkg/operator/config/crd/bases/mps.playfab.com_gameserverbuilds.yaml
  pkg/operator/config/crd/bases/mps.playfab.com_gameserverdetails.yaml
  pkg/operator/config/crd/bases/mps.playfab.com_gameservers.yaml
  pkg/operator/config/manager/manager.yaml
  pkg/operator/config/rbac/role.yaml
  pkg/operator/controllers/port_registry_test.go
  pkg/operator/controllers/suite_test.go
Labels: code-quality

#154 rename /data to /gsdkdata
  docs/development.md
  pkg/operator/controllers/utilities.go
  samples/data/Config/gsdkConfig.json
Labels: code-quality

#152 adding ResourceVersion in deletes
  pkg/operator/controllers/gameserverbuild_controller.go
Labels: code-quality

#150 replacing patch with update during allocation
  pkg/operator/http/allocate.go
Labels: code-quality
